### ISSUE TITLE
Cron stops suddenly and no emails are sent

### ISSUE THREAD

**Issue by seriema** [seriema/npmalerts#10]
It doesn't crash when there's a missing user repo, but it suddenly stops there.

Started happening after the Sep 25th, but the code hasn't been touched since Feb 4th. I updated Heroku to Cedar-14 on Sep 6th. My free logs with Logentries don't go back to September so I can't see if something special happened there, but the logs show the same behaviour for the past nights:

```
02:00:06.913 heroku api - - Starting process with command `node lib/cron.js` by scheduler@addons.heroku.com
02:00:07.920 heroku scheduler.3487 - - Starting process with command `node lib/cron.js`
02:00:08.514 heroku scheduler.3487 - - State changed from starting to up
02:00:09.461 heroku web.1 - - State changed from down to starting
02:00:09.531 heroku web.1 - - Unidling
02:00:10.725 heroku web.1 - - Starting process with command `node lib/web.js`
02:00:14.441 app web.1 - - express deprecated app.configure: Check app.get('env') in an if statement at lib/web.js:24:5
02:00:14.527 app web.1 - - express deprecated app.del: Use app.delete instead at lib/web.js:35:5
02:00:14.572 app web.1 - - connect deprecated methodOverride: use method-override npm module instead at lib/web.js:29:19
02:00:15.056 heroku web.1 - - State changed from starting to up
02:00:15.602 app web.1 - - 10.69.91.132 - - [05/Dec/2015:01:00:15 +0000] "GET /api/cron HTTP/1.1" 200 45 "-" "-"
02:00:15.616 heroku router - - at=info method=GET path="/api/cron" host=npmalerts.herokuapp.com request_id=54c67f53-cdd0-439b-902d-9c9b918696d6 fwd="54.234.255.9" dyno=web.1 connect=0ms service=21ms status=200 bytes=480
02:00:15.676 app scheduler.3487 - - Cron job started
02:00:15.681 app web.1 - - Starting check.
02:00:15.698 app web.1 - - Error processing user [removed for bug report] with repo [removed for bug report]. Skipped. Message: First argument needs to be a number, array or string.
02:01:16.325 heroku scheduler.3487 - - Process exited with status 0
02:01:16.369 heroku scheduler.3487 - - State changed from up to complete
02:31:57.210 heroku web.1 - - Idling
02:31:57.244 heroku web.1 - - State changed from down to starting
02:31:57.296 heroku web.1 - - State changed from up to down
02:31:58.166 heroku web.1 - - Starting process with command `node lib/web.js`
02:32:00.639 app web.1 - - express deprecated app.configure: Check app.get('env') in an if statement at lib/web.js:24:5
02:32:00.673 app web.1 - - connect deprecated methodOverride: use method-override npm module instead at lib/web.js:29:19
02:32:00.725 app web.1 - - express deprecated app.del: Use app.delete instead at lib/web.js:35:5
02:32:01.092 heroku web.1 - - State changed from starting to up
02:32:01.579 heroku web.1 - - Stopping all processes with SIGTERM
02:32:03.953 heroku web.1 - - Process exited with status 143
03:03:14.734 heroku web.1 - - Idling
03:03:14.842 heroku web.1 - - State changed from up to down
03:03:17.878 heroku web.1 - - Stopping all processes with SIGTERM
03:03:19.834 heroku web.1 - - Process exited with status 143
```

**Comment by seriema** [comment]
Updated dependencies and fixed some broken tests. Now it isn't failing on the Github API argument call (`First argument needs to be a number, array or string.`) at least, so now it fails because of rate limit (wish it was npmalert's popularity! but it's probably others on heroku). When it's gone through the users it seems to get stuck.

A few of these, and then it just stops. Maybe it's the `asyncMap` or some `callback` not being called.

```
app[web.1]: Error processing user [removed for bug report] with repo [removed for bug report]. Skipped. Message: {"message":"API rate limit exceeded for 50.16.62.20. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
```

**Comment by seriema** [comment]
Confirmed. Got an email! :tada:
